import http from 'node:http';
import {appendFileSync, createReadStream, statSync, writeFileSync} from 'node:fs';
import {networkInterfaces} from 'node:os';
import {fileURLToPath} from 'node:url';

const port = Number(process.env.DEMO_PORT || 8088);
const host = process.argv[2] || Object.values(networkInterfaces()).flat().find(ip => ip && ip.family === 'IPv4' && !ip.internal)?.address;
if (!host || !/^[a-zA-Z0-9.-]+$/.test(host)) throw new Error('Supply your Mac LAN IP: npm run demo:serve -- YOUR_LAN_IP');
const file = fileURLToPath(new URL('../assets/demo-h264-aac.mp4', import.meta.url));
const diagnostics = fileURLToPath(new URL('../playback-vvd.log', import.meta.url));
const size = statSync(file).size;
writeFileSync(diagnostics, '');
const server = http.createServer((req, res) => {
  if (req.method === 'POST' && req.url?.startsWith('/__playback-log?')) {
    const message = new URL(req.url, `http://${host}:${port}`).searchParams.get('message') || '';
    appendFileSync(diagnostics, `${new Date().toISOString()} ${message}\n`);
    res.writeHead(204).end();
    return;
  }
  if (req.url !== '/demo-h264-aac.mp4' || !['GET', 'HEAD'].includes(req.method)) {res.writeHead(404).end(); return;}
  let start = 0, end = size - 1;
  const range = req.headers.range;
  if (range) {
    const match = /^bytes=(\d*)-(\d*)$/.exec(range);
    if (!match || (!match[1] && !match[2])) {res.writeHead(416, {'Content-Range': `bytes */${size}`}).end(); return;}
    start = match[1] ? Number(match[1]) : Math.max(0, size - Number(match[2]));
    end = match[1] && match[2] ? Math.min(Number(match[2]), size - 1) : size - 1;
    if (start > end || start >= size) {res.writeHead(416, {'Content-Range': `bytes */${size}`}).end(); return;}
  }
  const headers = {'Content-Type': 'video/mp4', 'Accept-Ranges': 'bytes', 'Content-Length': end - start + 1};
  if (range) headers['Content-Range'] = `bytes ${start}-${end}/${size}`;
  res.writeHead(range ? 206 : 200, headers);
  if (req.method === 'HEAD') {res.end(); return;}
  const stream = createReadStream(file, {start, end});
  stream.on('error', () => res.destroy());
  res.on('close', () => stream.destroy());
  stream.pipe(res);
});
server.listen(port, '0.0.0.0', () => {
  const uri = `http://${host}:${port}/demo-h264-aac.mp4`;
  writeFileSync(new URL('../src/data/media.ts', import.meta.url),
    `// Generated by demo:serve. H.264 Baseline + AAC-LC test asset.\nexport const mediaSource = {uri: ${JSON.stringify(uri)}, diagnosticUri: ${JSON.stringify(`http://${host}:${port}/__playback-log`)}};\n`);
  console.log(`Serving demo at ${uri}\nUpdated src/data/media.ts. Playback diagnostics: ${diagnostics}`);
});
