import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join, relative, resolve} from 'node:path';
import {Resvg} from '@resvg/resvg-js';

type OfflineCard = {
  cueId: string;
  label: string;
  listenerHint: string;
  mainVoice?: {instrument: string; evidence: 'hauptstimme'; basis: string};
  activeInstruments: string[];
  work: {composer: string; title: string; movement: string};
};
type OfflineManifest = {cards: Array<{status: 'generated'; cueId: string; measure: number; timestampSec: number; region: {startSec: number; endSec: number}; renderWindow: {startMeasure: number; endMeasure: number}; path: string} | {status: 'failed'; cueId: string; measure: number; error: string}>};
export type GuidedListeningRuntimeCue = {
  id: string;
  startTime: number;
  endTime: number;
  measure: number;
  label: string;
  listenerHint: string;
  mainVoice?: {instrument: string; evidence: 'hauptstimme'};
  activeInstruments: string[];
  scoreAssetKey: string;
  work: {composer: string; title: string; movement: string};
};
export type GuidedListeningRuntimeManifest = {version: 1; workId: 'brahms-op68-4'; cues: GuidedListeningRuntimeCue[]};

const assetModule = (cues: readonly GuidedListeningRuntimeCue[]) => `/* Generated by tools/generateGuidedListeningRuntime.ts. Do not edit. */\nexport const brahmsGuidedListeningScoreAssets: Readonly<Record<string, number>> = {\n${cues.map(cue => `  ${JSON.stringify(cue.scoreAssetKey)}: require(${JSON.stringify(`../../assets/generated/guided-listening-card/brahms-op68-movement4/full/${cue.id}/score.png`)}),`).join('\n')}\n};\n`;

/** Converts offline Verovio SVG cards to static PNG assets and emits the compact TV runtime manifest. */
export function generateGuidedListeningRuntime(offlineDirectory: string, manifestOutput: string, assetsModuleOutput: string): GuidedListeningRuntimeManifest {
  const root = resolve(offlineDirectory);
  const offline = JSON.parse(readFileSync(join(root, 'manifest.json'), 'utf8')) as OfflineManifest;
  const cues = offline.cards.map(entry => {
    if (entry.status !== 'generated') throw new Error(`Cannot create runtime cue for failed ${entry.cueId}: ${entry.error}`);
    const directory = join(root, entry.path);
    const card = JSON.parse(readFileSync(join(directory, 'card.json'), 'utf8')) as OfflineCard;
    const svg = readFileSync(join(directory, 'score.svg'), 'utf8');
    const png = new Resvg(svg, {fitTo: {mode: 'width', value: 1200}, background: '#fffdf8'}).render().asPng();
    writeFileSync(join(directory, 'score.png'), png);
    return {
      id: entry.cueId,
      startTime: entry.region.startSec,
      endTime: entry.region.endSec,
      measure: entry.measure,
      label: card.label,
      listenerHint: card.listenerHint,
      ...(card.mainVoice ? {mainVoice: {instrument: card.mainVoice.instrument, evidence: card.mainVoice.evidence}} : {}),
      activeInstruments: card.activeInstruments,
      scoreAssetKey: entry.cueId,
      work: card.work,
    };
  });
  const runtime: GuidedListeningRuntimeManifest = {version: 1, workId: 'brahms-op68-4', cues};
  mkdirSync(dirname(resolve(manifestOutput)), {recursive: true});
  mkdirSync(dirname(resolve(assetsModuleOutput)), {recursive: true});
  writeFileSync(resolve(manifestOutput), `${JSON.stringify(runtime, null, 2)}\n`);
  writeFileSync(resolve(assetsModuleOutput), assetModule(cues));
  return runtime;
}

function main(): void {
  const [offlineDirectory, manifestOutput, assetsModuleOutput] = process.argv.slice(2);
  if (!offlineDirectory || !manifestOutput || !assetsModuleOutput) throw new Error('Usage: npm run generate:guided-listening-runtime -- <offline-card-dir> <runtime-manifest.json> <assets-module.ts>');
  const runtime = generateGuidedListeningRuntime(offlineDirectory, manifestOutput, assetsModuleOutput);
  process.stdout.write(`Generated ${runtime.cues.length} Guided Listening runtime cues.\n`);
}
if (process.argv[1]?.endsWith('generateGuidedListeningRuntime.ts')) main();
