import {mkdirSync, readFileSync, rmSync, writeFileSync} from 'node:fs';
import {join, relative, resolve} from 'node:path';
import {buildGuidedListeningCard, guidedListeningCardHtml, type GuidedListeningCard} from './generateGuidedListeningCard';
import {parseMeasure, parseScoreParts} from './generateSmartScorePrototype';
import {createVerovioToolkit, extractMusicXmlExcerptWithReport, validateSvgGlyphs, type ExcerptIntegrity, type ExcerptWindow, type SvgGlyphValidation} from './generateVerovioSmartScoreProof';
import {tvVerovioOptions} from './generateVerovioSmartScorePrototype';
import type {ListeningCue, ListeningCueManifest} from './generateListeningCues';
import type {ScoreManifest} from './generateScoreManifest';

type Complexity = {multipleVoices: boolean; tuplets: boolean; warnings: string[]};
type CardSuccess = {status: 'generated'; cueId: string; measure: number; timestampSec: number; region: {startSec: number; endSec: number}; label: string; mainVoice?: string; listenerHint: string; selectedStaves: string[]; renderWindow: ExcerptWindow; extractionWarnings: string[]; removedAnalyticalLyrics: number; normalizedOtherDynamics: number; integrity: ExcerptIntegrity; glyphValidation: SvgGlyphValidation; verovioWarnings: string[]; complexity: Complexity; semanticConsistency: boolean; noStrayAnalyticalLetters: boolean; path: string};
type CardFailure = {status: 'failed'; cueId: string; measure: number; error: string};
export type BrahmsGuidedListeningManifest = {generator: {version: 2; renderer: {name: 'Verovio'; version: string; options: Record<string, unknown>}; filtering: string}; cards: Array<CardSuccess | CardFailure>};

const work = {composer: 'Brahms', title: 'Symphony No. 1', movement: 'Movement IV'};
// A runtime card opens when its cue starts. Render forward from that exact
// source bar so the first visible notation is the music currently sounding.
const windowFor = (cue: ListeningCue): ExcerptWindow => ({startMeasure: cue.measure, endMeasure: cue.measure + 3});
const escapeHtml = (value: string) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const complexityFor = (source: string, staves: readonly string[], window: ExcerptWindow): Complexity => {
  const key = (name: string) => name.toLowerCase().replace(/[^a-z0-9]/g, ''); const selected = new Set(staves.map(key));
  const warnings = parseScoreParts(source).filter(part => selected.has(key(part.name))).flatMap(part => [...part.measures.entries()].filter(([number]) => number >= window.startMeasure && number <= window.endMeasure).flatMap(([number, xml]) => parseMeasure(xml).unsupported.map(warning => `${part.name}, m.${number}: ${warning}`)));
  return {multipleVoices: warnings.some(warning => warning.includes('Multiple voices')), tuplets: warnings.some(warning => warning.includes('Tuplets')), warnings: [...new Set(warnings)]};
};
const boundaryWarnings = (musicxml: string): string[] => {
  const count = (pattern: RegExp) => (musicxml.match(pattern) ?? []).length; const warnings: string[] = [];
  if (count(/<tie\b[^>]*type="start"/g) !== count(/<tie\b[^>]*type="stop"/g)) warnings.push('Excerpt boundary intersects an open MusicXML tie.');
  if (count(/<slur\b[^>]*type="start"/g) !== count(/<slur\b[^>]*type="stop"/g)) warnings.push('Excerpt boundary intersects an open MusicXML slur.');
  return warnings;
};
export async function generateBrahmsGuidedListeningCards(scorePath: string, scoreManifestPath: string, cuePath: string, outputDirectory: string): Promise<BrahmsGuidedListeningManifest> {
  const source = readFileSync(scorePath, 'utf8'); const score = JSON.parse(readFileSync(scoreManifestPath, 'utf8')) as ScoreManifest;
  const cues = JSON.parse(readFileSync(cuePath, 'utf8')) as ListeningCueManifest; const output = resolve(outputDirectory); rmSync(output, {recursive: true, force: true}); mkdirSync(output, {recursive: true}); const toolkit = await createVerovioToolkit(); toolkit.setOptions(tvVerovioOptions);
  const cards: Array<CardSuccess | CardFailure> = [];
  for (const cue of cues.cues) {
    try {
      const renderWindow = windowFor(cue); const extracted = extractMusicXmlExcerptWithReport(source, cue.recommendedStaves, renderWindow); const directory = join(output, cue.id); mkdirSync(directory, {recursive: true}); writeFileSync(join(directory, 'excerpt.musicxml'), `${extracted.musicxml}\n`);
      const loadStatus = toolkit.loadData(extracted.musicxml); if (loadStatus !== 1) throw new Error(`Verovio load status ${loadStatus}.`); const svg = toolkit.renderToSVG(1, {}); const glyphValidation = validateSvgGlyphs(svg, true); if (!glyphValidation.valid) throw new Error(`SVG glyph validation failed: ${glyphValidation.issues.join(' ')}`); writeFileSync(join(directory, 'score.svg'), svg);
      const card: GuidedListeningCard = buildGuidedListeningCard(cue, score, 'score.svg', work); writeFileSync(join(directory, 'card.json'), `${JSON.stringify(card, null, 2)}\n`); writeFileSync(join(directory, 'review.html'), guidedListeningCardHtml(card));
      const warnings = [...boundaryWarnings(extracted.musicxml), ...(extracted.removedAnalyticalLyrics ? [`Removed ${extracted.removedAnalyticalLyrics} red single-character analytical lyric annotation(s).`] : [])]; const complexity = complexityFor(source, cue.recommendedStaves, renderWindow); const noStrayAnalyticalLetters = !/#(?:ff)?0000/i.test(svg) && !/class="verse"/.test(svg); const verovioWarnings = toolkit.getLog().split('\n').map(line => line.trim()).filter(Boolean).map(line => line.replace(/'[^']+'/g, "'<generated-id>'"));
      cards.push({status: 'generated', cueId: cue.id, measure: cue.measure, timestampSec: cue.timestampSec, region: cue.region, label: cue.label, mainVoice: card.mainVoice?.instrument, listenerHint: card.listenerHint, selectedStaves: [...cue.recommendedStaves], renderWindow, extractionWarnings: warnings, removedAnalyticalLyrics: extracted.removedAnalyticalLyrics, normalizedOtherDynamics: extracted.normalizedOtherDynamics, integrity: extracted.integrity, glyphValidation, verovioWarnings, complexity, semanticConsistency: cue.staffConsistency.valid, noStrayAnalyticalLetters, path: relative(output, directory)});
    } catch (error) { cards.push({status: 'failed', cueId: cue.id, measure: cue.measure, error: error instanceof Error ? error.message : String(error)}); }
  }
  const manifest: BrahmsGuidedListeningManifest = {generator: {version: 2, renderer: {name: 'Verovio', version: toolkit.getVersion(), options: tvVerovioOptions}, filtering: 'Remove only red, single-character synthetic analysis lyrics from instrumental parts. Preserve vocal lyrics and musical text. Normalize MusicXML other-dynamics text into an equivalent words direction so the dynamic and expression remain portable through SVG-to-PNG rasterization.'}, cards}; writeFileSync(join(output, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  const successes = cards.filter((card): card is CardSuccess => card.status === 'generated'); const failures = cards.filter((card): card is CardFailure => card.status === 'failed'); const boundaryWarningCards = successes.filter(card => card.extractionWarnings.some(warning => !warning.startsWith('Removed '))).length; const tupletCards = successes.filter(card => card.complexity.tuplets).length; const multipleVoiceCards = successes.filter(card => card.complexity.multipleVoices).length; const verovioWarningCards = successes.filter(card => card.verovioWarnings.length > 0).length; const semanticFailures = successes.filter(card => !card.semanticConsistency).length; const integrityFailures = successes.filter(card => !card.integrity.valid).length; const glyphFailures = successes.filter(card => !card.glyphValidation.valid).length; const lines = ['# Brahms Guided Listening Cards', '', `Total Listening Cues: ${cues.cues.length}`, `Generated cards: ${successes.length}`, `Generation failures: ${failures.length}`, `Cards with Hauptstimme MAIN VOICE: ${successes.filter(card => card.mainVoice).length}`, `Cards without MAIN VOICE: ${successes.filter(card => !card.mainVoice).length}`, `Analytical lyric annotations removed: ${successes.reduce((total, card) => total + card.removedAnalyticalLyrics, 0)}`, `other-dynamics expressions normalized: ${successes.reduce((total, card) => total + card.normalizedOtherDynamics, 0)}`, `Source/excerpt integrity failures: ${integrityFailures}`, `SVG glyph validation failures: ${glyphFailures}`, `Stray colored analytical letters remaining: ${successes.filter(card => !card.noStrayAnalyticalLetters).length}`, `Cards with boundary tie/slur warnings: ${boundaryWarningCards}`, `Cards with Verovio warnings: ${verovioWarningCards}`, `Cards with multiple-voice complexity: ${multipleVoiceCards}`, `Cards with tuplet complexity: ${tupletCards}`, `Semantic-consistency failures: ${semanticFailures}`, '', '## Per-cue report', ''];
  for (const card of cards) { if (card.status === 'failed') { lines.push(`### m.${card.measure} — FAILED`, '', card.error, ''); continue; } lines.push(`### m.${card.measure} — ${card.label}`, '', `Hint: ${card.listenerHint}`, '', `Main Voice: ${card.mainVoice ?? 'none'}`, '', `Staves: ${card.selectedStaves.join(', ')}`, '', `Window: m.${card.renderWindow.startMeasure}–${card.renderWindow.endMeasure}`, '', `Integrity: ${card.integrity.valid ? 'PASS' : `FAIL — ${card.integrity.mismatches.join(' ')}`}`, '', `SVG glyph validation: ${card.glyphValidation.valid ? 'PASS' : `FAIL — ${card.glyphValidation.issues.join(' ')}`}`, '', `Verovio warnings: ${card.verovioWarnings.join(' ') || 'none recorded'}`, '', `Boundary/extraction warnings: ${card.extractionWarnings.join(' ') || 'none'}`, '', `Complexity: ${card.complexity.warnings.join(' ') || 'no multi-voice or tuplet warning'}`, '', `Semantic consistency: ${card.semanticConsistency ? 'PASS' : 'FAIL'}`, ''); }
  writeFileSync(join(output, 'report.md'), `${lines.join('\n')}\n`);
  const contactCards = successes.map(card => `<article><header><b>m.${card.measure}</b><span>${escapeHtml(card.label)}</span></header><iframe src="${escapeHtml(card.path)}/review.html" title="${escapeHtml(card.cueId)}"></iframe></article>`).join(''); writeFileSync(join(output, 'contact-sheet.html'), `<!doctype html><meta charset="utf-8"><title>Brahms Guided Listening Cards</title><style>body{margin:24px;background:#09111a;color:#edf4fc;font:16px system-ui}h1{color:#f1c46d}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}article{background:#1b2733;padding:10px;border-radius:8px;overflow:hidden}header{display:flex;gap:8px;align-items:baseline;margin:2px 2px 8px;color:#c9d7e0}header b{color:#f1c46d}iframe{width:1280px;height:720px;border:0;transform:scale(.27);transform-origin:top left;pointer-events:none}.grid article{height:215px}@media(max-width:1100px){.grid{grid-template-columns:repeat(2,1fr)}}</style><h1>Brahms 1 / IV · Guided Listening Cards</h1><p>26 generated cards in performance order. Each preview is the unedited 1280 × 720 card template.</p><section class="grid">${contactCards}</section>`);
  return manifest;
}

async function main(): Promise<void> { const [score, scoreManifest, cues, output] = process.argv.slice(2); if (!score || !scoreManifest || !cues || !output) throw new Error('Usage: npm run generate:brahms-guided-listening -- <score.musicxml> <score-manifest.json> <listening-cues.json> <output-dir>'); const result = await generateBrahmsGuidedListeningCards(score, scoreManifest, cues, output); process.stdout.write(`Generated ${result.cards.filter(card => card.status === 'generated').length}/${result.cards.length} Guided Listening Cards.\n`); }
if (process.argv[1]?.endsWith('generateBrahmsGuidedListeningCards.ts')) void main();
